### ISSUE TITLE
chromedriver

### ISSUE THREAD

**Issue by stevencheung** [Juphex/SupremeBot#18]
Hi, I'm interested to build a crawler for Android using python and selenium, and would like to learn how you developed SupremeBot. I've tried to build SupremeBot using kivy/buildozer and to install and run it on an Android emulator. However, the app didn't run. In the process of reading and understanding your code, I noticed that it uses a chromedriver.exe (a Windows executable). Thus, it appears that the chromedriver is not run on Android. Would you mind explaining to me how that chromedriver.exe is used by the crawler in SupremeBot? Thanks a lot!

**Comment by Juphex** [comment]
Hi!
Yes, I use an executable to run the browser (Chrome) on windows. I think I have not tested it on android, since an .exe would not work I guess. You can try out Selendroid and if that fails maybe the Android in-built webview which could be accessed by pyjnius. I hope that that may help you 👍  Keep in mind that testing will be more time consuming on android thats why I stopped this project

**Comment by stevencheung** [comment]
I don't know if I may find a chromedriver for Android. That might be a show stopper for running everything on Android. Thanks a lot for your suggestions! I'll look into them.
